// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAirbnb.Data;

namespace MyAirbnb.Migrations
{
    [DbContext(typeof(AirbnbDbContext))]
    partial class AirbnbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyAirbnb.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("EspacoM2")
                        .HasColumnType("real");

                    b.Property<DateTime>("HoraCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCamas")
                        .HasColumnType("int");

                    b.Property<float>("PrecoPorNoite")
                        .HasColumnType("real");

                    b.Property<bool>("TemCozinha")
                        .HasColumnType("bit");

                    b.Property<bool>("TemJacuzzi")
                        .HasColumnType("bit");

                    b.Property<bool>("TemPiscina")
                        .HasColumnType("bit");

                    b.Property<string>("TipoImovel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("MyAirbnb.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataDeFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImovelID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImovelID");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("MyAirbnb.Models.Reserva", b =>
                {
                    b.HasOne("MyAirbnb.Models.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
